_wandb:
    value:
        cli_version: 0.19.5
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 12
                - 53
                - 55
            "2":
                - 1
                - 2
                - 3
                - 5
                - 12
                - 53
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.12.7
            "5": 0.19.5
            "8":
                - 5
                - 13
            "12": 0.19.5
            "13": darwin-arm64
data_config:
    value: /Users/bleile/Master/Thesis Work/CausalDiffusion/config/dev/linear20.yaml
model_config:
    value: /Users/bleile/Master/Thesis Work/CausalDiffusion/config/dev/models.yaml
seed:
    value: 100
